[build]
  command = "npm run build"
  publish = "admin/dist"
  functions = "netlify/functions"

[dev]
  command = "vite"
  port = 8888
  targetPort = 5173
  publish = "admin/dist"
  autoLaunch = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
